/* Info: This file is for API endpoint constants */
/* Created on {3-07-19} By {Pravesh Sharma}*/
/* Modified on {19-07-19} By {Pravesh Sharma}*/

export const ApiConst = {
  BASE_URL: 'https://app.scoop.ai/',

  //// Updates - 18th April 2020 ////////
  BASE_URL_PLUGINS: 'https://plugins.scoop.ai/',

  LOGIN: 'api/v2/login',
  //OPPORTUNITY_CONVERSION: 'api/v2/home/last_day/opportunity_isto_conversion',
  TOTAL_CONVERSATION:'api/v2/home/last_day_metrics',
  //MISSED_OPPORTUNITY: 'api/v2/home/last_day/missed_opportunities',
  // TOTAL_OPPORTUNITY: 'api/v2/home/last_day/total_opportunities',
  //NEGATIVE_CONVERSATION: 'api/v2/home/last_day/negative_conversation',
  // BANT_MENTION:'api/v2/home/last_day/bant_mentions',
  //ROUGE_CONVERSATION: 'api/v2/home/last_day/rogue_conversation',
  // PRICING_MENTION:'api/v2/home/last_day/pricing_mentions',
  CONVERSATIONS: 'api/v2/home/key_metrics/conversations',
  MOST_DISCUSSED_TOPICS: 'api/v2/home/key_metrics/most_discussed_topics',
  ACTIVITY_STREAM: '/api/v2/home/key_metrics/activity_stream',
  RECENTLY_UPDATED_COLLECTION: 'api/v2/home/key_metrics/recently_updated_collections',
  DEFAULT_LISTING: 'api/v2/conversations/read-all',
  SEARCH: 'api/v2/conversations/search',
  SEARCH_FILTER: 'api/v2/conversations/search/filter',
  REP_BY_CHANNEL_ID: 'api/v2/conversations/search/filter/reps',
  READ_ALL_COLLECTION: 'api/v2/collections/read-all',
  READ_COLLECTION: 'api/v2/collections/read',
  CREATE_COLLECTION: 'api/v2/collections/create',
  DELETE_COLLECTION: 'api/v2/collections/delete',
  STAR_CONVERSATION: 'api/v2/conversations/update',
  READ_MANUAL_COLLECTION: 'api/v2/collections/manual/read-all',
  BOOKMARK_CONVERSATION: 'api/v2/collections/manual/add',
  REMOVE_CONVERSATION: 'api/v2/collections/manual/delete',
  UPDATE_COLLECTION: 'api/v2/collections/update',
  RECENTLY_SAVED_COLLECTION: 'api/v2/collections/recently/read',
  STARRED_CONVERSATION: 'api/v2/collections/starred/read',
  CONVERSATIONS_DETIAL: 'api/v2/conversations/read',
  UPDATE_READ: 'api/v2/profile/read',
  UPDATE_PROFILE: 'api/v2/profile/update',
  CHANGE_PASSWORD: 'api/v2/profile/change_password',
  COLLECTION_EXIST: 'api/v2/collections/exists',
  CONVERSATION_UPDATE: 'api/v2/conversations/update',
  LOGOUT: 'api/v2/logout',
  HIERARCHY: 'api/v2/user/hierarchy',
  REFRESH_TOKEN: 'api/v2/refresh_token',
  TOPICS_READ: 'api/v2/configure/topics/read-all',
  CREATE_TOPIC: 'api/v2/configure/topics/create',
  UPDATE_TOPIC: 'api/v2/configure/topics/update',
  DELETE_TOPIC: 'api/v2/configure/topics/delete',

  //// Updates - 18th April 2020 ////////
  PUGINS_LIST: 'api/v2/platforms',
  PLUGIN_AUTH: 'api/v2/auth',
  PLUGIN_REPS: 'api/v2/reps',
  PLUGIN_SYNC: 'api/v2/sync',
  READ_PLUGIN_DATA: 'api/v2/channels',


  // INSIGHT_CONVERSATION_TOTAL: 'api/v2/dashboard/conversation/total_conversations_card',
  INSIGHT_CONVERSATION_TOTAL: 'api/v2/dashboard/conversation/total_questions',
  // INSIGHT_CONVERSATION_OPPORTUNITY: 'api/v2/dashboard/conversation/total_opportunity_card',
  INSIGHT_CONVERSATION_OPPORTUNITY: 'api/v2/dashboard/conversation/total_highest_switches',
  // INSIGHT_CONVERSATION_PURCHASE_STAGE: 'api/v2/dashboard/conversation/purchase_stage_card',
  INSIGHT_CONVERSATION_PURCHASE_STAGE: 'api/v2/dashboard/conversation/total_high_dead_air',

  INSIGHT_CONVERSATION_PRICING_MENTION: 'api/v2/dashboard/conversation/negative',
  // INSIGHT_REPS_TOTAL: 'api/v2/dashboard/representative/total_conversations_card',
  INSIGHT_REPS_TOTAL: 'api/v2/dashboard/representative/active_reps',

  // INSIGHT_REPS_FOLLOWUPS: 'api/v2/dashboard/representative/follow_ups_card',
  INSIGHT_REPS_FOLLOWUPS: 'api/v2/dashboard/representative/reps_with_opportunity',

  // INSIGHT_REPS_ROGUE: 'api/v2/dashboard/representative/rogue_conversations_card',
  INSIGHT_REPS_ROGUE: 'api/v2/dashboard/representative/reps_with_golden_ratio',

  // INSIGHT_REPS_DEAD_AIR: 'api/v2/dashboard/representative/dead_air_conversations_card',
  INSIGHT_REPS_DEAD_AIR: 'api/v2/dashboard/representative/reps_with_high_dead_air',

  INSIGHT_CUSTOMER_TOTAL: 'api/v2/dashboard/customer/total_conversations_card',
  INSIGHT_CUSTOMER_TOTAL_NEGATIVE: 'api/v2/dashboard/customer/total_negative_sentiment_card',
  INSIGHT_CUSTOMER_TOTAL_PROBLEM: 'api/v2/dashboard/customer/total_problems_cards',
  INSIGHT_CUSTOMER_TOTAL_PRICE_SENSITIVE: 'api/v2/dashboard/customer/total_price_sensitive_card',
  INSIGHT_CUSTOMER_CONVERSATIONS: 'api/v2/dashboard/customer/conversations',
  INSIGHT_CUSTOMER_SENTIMENT_LEVEL: 'api/v2/dashboard/customer/sentiment_level',
  INSIGHT_CUSTOMER_FOLLOW_UPS: 'api/v2/dashboard/customer/follow_ups',
  INSIGHT_CUSTOMER_FOLLOW_UPS_APPOINTMENT: 'api/v2/dashboard/customer/follow_ups_and_appointments',
  INSIGHT_CUSTOMER_APPOINTMENT: 'api/v2/dashboard/customer/appointments',
  INSIGHT_REPS_SENTIMENT_LEVEL: 'api/v2/dashboard/representative/sentiment_level',
  INSIGHT_REPS_WISE_OPPORTUNITY: 'api/v2/dashboard/representative/rep_wise_opportunity',
  INSIGHT_CUSTOMER_TONE: 'api/v2/dashboard/customer/tone',
  INSIGHT_REPS_FOLLOW_UPS: 'api/v2/dashboard/representative/follow_ups',
  INSIGHT_REPS_APPOINTMENTS: 'api/v2/dashboard/representative/appointments',
  INSIGHT_REPS_FOLLOWUPAPPOINTMENT: 'api/v2/dashboard/representative/follow_ups_and_appointments',
  INSIGHT_REPS_DASHBOARD_GRAPH: 'api/v2/dashboard/representative/rep_wise_performance',
  INSIGHT_CONVERSATION_REP_WISE_PERFORMANCE: 'api/v2/dashboard/conversation/rep_wise_performance',
  INSIGHT_CONVERSATION_OPPORTUNITY_STAGE: 'api/v2/dashboard/conversation/opportunity_stage',

  // INSIGHT_CONVERSATION_GRAPH: 'api/v2/dashboard/conversation/conversations',
  INSIGHT_CONVERSATION_GRAPH:'api/v2/dashboard/conversation/conversations_with_opportunity',

  INSIGHT_CONVERSATION_DURATION: 'api/v2/dashboard/conversation/duration',
  INSIGHT_CONVERSATION_PEAKDAYTIME: 'api/v2/dashboard/conversation/peak_day_time',
  CONFIGURE_USERS_LIST: 'api/v2/configure/users/read-all',
  CONFIGURE_ROLES_READ_ALL: 'api/v2/configure/roles/read-all',
  CONFIGURE_USERS_CREATE_USER: 'api/v2/configure/users/create',
  CONFIGURE_USERS_UPDATE_USER: 'api/v2/configure/users/update',
  CONFIGURE_ROLES_ACCESS_OBJECT: 'api/v2/configure/roles/form_field_value',
  CONFIGURE_ROLES_CREATE: 'api/v2/configure/roles/create',
  CONFIGURE_USERS_DELETE_USER: 'api/v2/configure/users/delete',
  CONFIGURE_ORGANIZATION_HIERARCHY: 'api/v2/configure/organization_hierarchy',
  CONFIGURE_ROLES_UPDATE: 'api/v2/configure/roles/update',
  CONFIGURE_ROLES_DELETE: 'api/v2/configure/roles/delete',
  INSIGHT_CONVERSATION_BLOCKS: 'api/v2/dashboard/conversation/pre_defined_topics',
  INSIGHT_CUSTOMER_BLOCKS: 'api/v2/dashboard/customer/pre_defined_topics',
  INSIGHT_CUSOMER_CONTATCTABILITY: 'api/v2/dashboard/customer/contactability',
  NOTIFICATION_FETCH:'api/v2/notifications/fetch',
  NOTIFICATION_CLEAR: 'api/v2/notifications/clear',
  NOTIFICATION_MARK_READ:'api/v2/notifications/mark-read',

  //// Updates - 18th April 2020 ////////
  DEAUTHINTEGRATION:'api/v2/deauth',
  TOPICTRENDS: 'api/v2/dashboard/conversation/topic_trends',
  INSIGHT_CUSTOM_TOPICS: 'api/v2/dashboard/conversation/custom_topics',
  INSIGHT_CONVERSATION_TOPICS: 'api/v2/dashboard/conversation/topic_keywords',
  CONVERSATIONHIGHLIGHTS: 'api/v2/dashboard/conversation/highlights',
  BANT_CONV: 'api/v2/dashboard/conversation/bant',
  CONNECT_CONV: 'api/v2/dashboard/conversation/connect',
  FEEDBACK_DASH: 'api/v2/home/key_metrics/feedback_stream'
};
